openapi: 3.0.3
info:
  title: Pricing Service API
  description: API to retrieve pricing information for products
  version: 1.0.0
paths:
  /api/prices:
    get:
      operationId: getApplicablePrice
      summary: Get applicable price for a product
      tags:
        - pricing
      parameters:
        - name: applicationDate
          in: query
          required: true
          description: Date and time for which the price is being queried
          schema:
            type: string
        - name: productId
          in: query
          required: true
          description: Product identifier
          schema:
            type: integer
            format: int64
        - name: brandId
          in: query
          required: true
          description: Brand identifier
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Applicable price information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '404':
          description: No applicable price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    PriceResponse:
      type: object
      required:
        - productId
        - brandId
        - priceList
        - startDate
        - endDate
        - price
        - currency
      properties:
        productId:
          type: integer
          format: int64
          description: Product identifier
        brandId:
          type: integer
          format: int64
          description: Brand identifier
        priceList:
          type: integer
          format: int32
          description: Price list identifier
        startDate:
          type: string
          description: Start date of the price application
        endDate:
          type: string
          description: End date of the price application
        price:
          type: number
          format: double
          description: Final price
        currency:
          type: string
          description: Currency code

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
        details:
          type: string
          description: Detailed error information